### ISSUE TITLE
Enable automatic deployment to gh-pages

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.com#37]
See http://moox.io/statinamic/docs/usage/gh-pages/

**Comment by marcustisater** [comment]
@MoOx - Auto deployment seems to override the entire repository including the CNAME file. Any work-arounds?

**Comment by MoOx** [comment]
Let me double check.

**Comment by MoOx** [comment]
Publish looks good https://github.com/postcss/postcss.com/tree/gh-pages here
You just didn't finish the automatic step http://moox.io/statinamic/docs/usage/gh-pages/#automatically-with-travis-ci
Also, since you are testing on multiples node version, you will need to deploy on for a certain version of node, like this https://github.com/MoOx/statinamic/blob/master/.travis.yml#L13-L19 (note that you don't need "docs/" in paths.

**Comment by MoOx** [comment]
And for the CNAME, you might need something like this https://github.com/putaindecode/putaindecode.io/blob/master/package.json#L79 (adjust the script name)

**Comment by MoOx** [comment]
What happen you run "npm run deploy" by hand?

**Comment by marcustisater** [comment]
It runs great from local, everything is running as expected. I forgot to adjust the script to add the CNAME file and setting up the Travis-Cli with this one as well, just wanted to try out npm run deploy one. Thanks for fast response.

**Comment by marcustisater** [comment]
I'm probably doing this all wrong or just missing something very important, it's late :tired_face: Can you double check this for me? Thanks.

**Comment by MoOx** [comment]
I will fix that into master directly

**Comment by MoOx** [comment]
Ok master is almost ready, it just seems I mentionned an example with GITHUB_TOKEN  instead of GH_TOKEN. I updated master this way, should fix it. Finger crossed.

**Comment by MoOx** [comment]
WOOT. That's it http://postcss.com/

**Comment by MoOx** [comment]
I will update statinamic docs according to this experience.

**Comment by marcustisater** [comment]
Whoop whoop! Thanks for fixing this :smile:
